In [1]:
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

num_classes = 2
resnet_weights_path = '/content/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5'

my_new_model = Sequential()
my_new_model.add(ResNet50(include_top=False, pooling='avg', weights=resnet_weights_path))
my_new_model.add(Dense(num_classes, activation='softmax'))

# Say not to train first layer (ResNet) model. It is already trained
my_new_model.layers[0].trainable = False

my_new_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 resnet50 (Functional)       (None, 2048)              23587712  
                                                                 
 dense (Dense)               (None, 2)                 4098      
                                                                 
Total params: 23591810 (90.00 MB)
Trainable params: 4098 (16.01 KB)
Non-trainable params: 23587712 (89.98 MB)
_________________________________________________________________


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
my_new_model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

In [5]:
!unzip /content/urbanandrural.zip -d /content/Data

Archive:  /content/urbanandrural.zip
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural1.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural11.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural12.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural13.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural14.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural16.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural17.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural18.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural19.jpg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural2.jpeg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural21.jpg  
  inflating: /content/Data/rural_and_urban_photos/train/rural/rural22.jpeg  
  inflating: /content/Data/rural_and_urban_

In [6]:
from tensorflow.keras.applications.resnet50 import preprocess_input
from keras.preprocessing.image import ImageDataGenerator


image_size = 224
data_generator = ImageDataGenerator(preprocessing_function=preprocess_input)


train_generator = data_generator.flow_from_directory(
        '/content/Data/rural_and_urban_photos/train',
        target_size=(image_size, image_size),
        batch_size=12,
        class_mode='categorical')

validation_generator = data_generator.flow_from_directory(
        '/content/Data/rural_and_urban_photos/val',
        target_size=(image_size, image_size),
        batch_size=20,
        class_mode='categorical')

Found 72 images belonging to 2 classes.
Found 20 images belonging to 2 classes.


In [7]:
my_new_model.fit(
        train_generator,
        steps_per_epoch=6,
        validation_data=validation_generator,
        validation_steps=1)

6/6 [==============================] - 25s 3s/step - loss: 0.3178 - accuracy: 0.8750 - val_loss: 0.2687 - val_accuracy: 0.8500


In [12]:
import tensorflow as tf
import numpy as np

In [18]:
# prompt: code to convert urban_5.jpeg in content to an array using numpy
def imgarr(path):
 img = tf.keras.preprocessing.image.load_img(path, target_size=(224, 224))
 x = tf.keras.preprocessing.image.img_to_array(img)
 x = np.expand_dims(x, axis=0)
 return(x)


In [16]:
my_new_model.predict(x)

1/1 [==============================] - 1s 1s/step


array([[4.0001405e-04, 9.9959999e-01]], dtype=float32)

In [28]:
my_new_model.predict(imgarr('/content/Data/train/rural/rural1.jpeg'))

1/1 [==============================] - 0s 320ms/step


array([[0.8228001 , 0.17719993]], dtype=float32)

In [29]:
my_new_model.predict(imgarr('/content/Data/train/rural/rural11.jpeg'))

1/1 [==============================] - 0s 185ms/step


array([[0.8018154 , 0.19818455]], dtype=float32)

In [30]:
my_new_model.predict(imgarr('/content/Data/train/urban/urban_1.jpeg'))

1/1 [==============================] - 0s 188ms/step


array([[0.00544347, 0.99455655]], dtype=float32)

In [31]:
my_new_model.predict(imgarr('/content/Data/train/urban/urban_11.jpeg'))

1/1 [==============================] - 0s 299ms/step


array([[0.00192741, 0.9980726 ]], dtype=float32)